[package]
name = "fire_spread"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.7.0"
glam = "0.20.5"
rand = "0.8.5"

[profile.dev.package.'*']
opt-level = 3